Update README.md
education/codespaces-project-template-py pull request #43
Opened 2023-06-17 21:01 UTC by Corttezz

Review and update to include the new Copilot section added to the Python template for repo (pt-BR).

2023-06-29 14:27 UTC, cyz commented
thank you @Corttezz , I will review your PR and back soon!

2023-06-29 19:11 UTC, cyz commented on translations/pt-BR/README.md
> +Ao abrir este modelo de repositório no Codespaces, você pode rapidamente experimentar um aplicativo da web Python que serve uma API HTTP. Você poderá se concentrar no trabalho com o projeto em vez de
Sugestão: "você poderá, rapidamente, desenvolver um aplicativo da web Python que serve uma API HTTP."

2023-06-29 19:13 UTC, cyz commented on translations/pt-BR/README.md
> +3. Aceite o desafio e implante seu aplicativo no Azure.
Sugestão: "Aceite o desafio e publique seu aplicativo no Azure."

2023-06-29 19:17 UTC, cyz commented on translations/pt-BR/README.md
> +- [webapp/](./.webapp): O código da API HTTP, construído com o framework FastAPI.
a pasta webapp não tem . no nome

2023-06-29 19:18 UTC, cyz commented on translations/pt-BR/README.md
> +- [.devcontainer/Dockerfile](./.devcontainer/Dockerfile): Arquivo de configuração usado pelo Codespaces para determinar o sistema operacional e outros detalhes.
verificar o link da pasta devcontainer (verificar se esta navegando para pasta raiz do projeto para acessar corretamente)

2023-06-29 19:19 UTC, cyz commented on translations/pt-BR/README.md
> +- [.devcontainer/devcontainer.json](./.devcontainer/devcontainer.json): Um arquivo de configuração usado pelo Codespaces para configurar as configurações do [Visual Studio Code](https://visualstudio.
mesmo cenário acima, verificar o link da pasta devcontainer (verificar se esta navegando para pasta raiz do projeto para acessar corretamente)

2023-06-29 19:26 UTC, cyz commented on translations/pt-BR/README.md
Por favor, poderia adicionar um details para explicar o que é um ponto de extremidade? Com base [nesta página de learn](https://learn.microsoft.com/pt-br/azure/machine-learning/concept-endpoints?view=azureml-api-2#endpoints-and-deployments), podemos utilizar o texto:

Um ponto de extremidade é uma URL estável e durável que pode ser usada para solicitar ou invocar o modelo, fornecer as entradas necessárias e obter as saídas de volta. Um ponto de extremidade fornece:

* Uma URL estável e durável (como **coloque o link da API de tempo indicada acima no tutorial**).
* Um mecanismo de autenticação e autorização.
Uma implantação é um conjunto de recursos necessários para hospedar o modelo que executa a inferência real. Um único ponto de extremidade pode conter várias implantações que podem hospedar ativos independentes e consumir recursos diferentes com base no que os ativos reais exigem. Os pontos de extremidade têm um mecanismo de roteamento que pode rotear a solicitação gerada para os clientes para implantações específicas no ponto de extremidade.

Para funcionar corretamente, cada ponto de extremidade precisa ter pelo menos uma implantação, ou seja, estar publicado e acessível.

2023-06-29 19:29 UTC, cyz commented on translations/pt-BR/README.md
> +A API incluída neste modelo de repositório possui um único endpoint que gera um token. Coloque-a em funcionamento seguindo as etapas a seguir:
utilize: ponto de extremidade (endpoint) para referências como esta, dentro do tutorial

2023-06-29 19:40 UTC, cyz commented on translations/pt-BR/README.md
> +Você pode alterar o seu ambiente e o editor de texto para que, da próxima vez que você criar (ou reconstruir) o ambiente, tudo seja configurado automaticamente. Vamos passar por dois desafios diferen
Sugestão: "Vamos abordar dois desafios diferentes e que você provavelmente deseja fazer:"

2023-06-29 19:40 UTC, cyz commented on translations/pt-BR/README.md
> +1. Alterando a versão do Python
Alterar a versão do Python instalada

2023-06-29 19:41 UTC, cyz commented on translations/pt-BR/README.md
> +2. Adicionando ou modificando uma extensão do editor pré-instalada
Adicionar ou modificar uma extensão do editor pré-instalada

2023-06-29 19:41 UTC, cyz commented on translations/pt-BR/README.md
> +### Passo 1: Alterar o ambiente do Python
Passo 1: Alterar a versão do Python instalada

2023-06-29 19:43 UTC, cyz commented on translations/pt-BR/README.md
> +Abra o arquivo [.devcontainer/devcontainer.json](./.devcontainer/devcontainer.json) e substitua a seguinte seção:
rever o link de navegação para página do devcontainer

2023-06-29 19:43 UTC, cyz commented on translations/pt-BR/README.md
> +Clique em "Rebuild". Aguarde o seu Codespace reconstruir o ambiente do VS Code.
Clique em Rebuild (em português, "Reconstruir").

2023-06-29 19:44 UTC, cyz commented on translations/pt-BR/README.md
> +### Passo 2: Adicionar uma extensão
Passo 2: Adicionar ou modificar uma extensão do editor pré-instalada

2023-06-29 19:45 UTC, cyz commented on translations/pt-BR/README.md
> +1. Abra o arquivo [.devcontainer/devcontainer.json](./.devcontainer/devcontainer.json) e localize o seguinte elemento JSON **extensions**:
rever o link de navegação para página do devcontainer

2023-06-29 19:46 UTC, cyz commented on translations/pt-BR/README.md
> +   Clique em "Rebuild". Aguarde o seu Codespace reconstruir o ambiente do VS Code.
Clique em Rebuild (em português, "Reconstruir").

2023-06-29 19:49 UTC, cyz commented on translations/pt-BR/README.md
> +Este repositório do Codespaces já tem a extensão Copilot habilitada. Verifique se sua conta tem acesso a ela. Se você não tiver acesso, pode [solicitar](https://github.com/login?return_to=%2fgithub-c
Vamos incluir o artigo em português:
[seguindo estas instruções](https://aka.ms/copilot-estudantes)

2023-06-29 19:50 UTC, cyz commented on translations/pt-BR/README.md
> +<summary><b>Usar o Copilot</b></summary>
"Utilizando o Copilot"

2023-06-29 19:53 UTC, cyz commented on translations/pt-BR/README.md
> +### Passo 4: Adicionar um novo endpoint à API
Passo 4: Adicionar um novo ponto de extremidade (endpoint) à API

2023-06-29 19:54 UTC, cyz commented on translations/pt-BR/README.md
> +Agora vamos adicionar uma nova funcionalidade à API. Adicione um novo endpoint à API que aceite um texto e retorne uma lista de tokens. Adicione o seguinte comentário para que o Copilot possa gerar u
Adicione um novo ponto de extremidade (endpoint) à API que aceite um texto e retorne uma lista de tokens.

2023-06-29 19:55 UTC, cyz commented on translations/pt-BR/README.md
> +Por fim, verifique se o novo endpoint está funcionando acessando a página `/docs` e testando o novo endpoint.
ponto de extremidade (endpoint)

2023-06-29 19:57 UTC, cyz commented on translations/pt-BR/README.md
> +Leve essa aplicação da API para o próximo nível e faça o deploy na nuvem! Para este desafio de aprendizado, você usará uma opção de implantação GRATUITA no Azure e o GitHub Actions para a automação.
Leve essa aplicação da API para o próximo nível e faça a sua publicação na nuvem! Para este desafio de aprendizado, você usará uma opção para publicar GRATUITAMENTE no Azure e o GitHub Actions para a automação.

2023-06-29 19:58 UTC, cyz commented on translations/pt-BR/README.md
> +Agora você irá configurar a implantação automática da aplicação usando o Azure e o GitHub Actions! No entanto, primeiro você precisa configurar alguns serviços do Azure.
Agora você irá configurar a publicação automática da aplicação usando o Azure e o GitHub Actions!

2023-06-29 19:59 UTC, cyz commented on translations/pt-BR/README.md
> +2. Use o shell Bash (não o PowerShell!) para executar estas etapas.
ajustar para "Bash shell"

2023-06-29 20:02 UTC, cyz commented on translations/pt-BR/README.md
> +A seguir, crie um Principal de Serviço do Azure, que é um tipo especial de conta que possui as permissões necessárias para autenticação do GitHub no Azure:
Azure Service Principal

2023-06-29 20:02 UTC, cyz commented on translations/pt-BR/README.md
> +<summary><b>Criar um Principal de Serviço do Azure</b></summary>
Criando um Azure Service Principal

2023-06-29 20:02 UTC, cyz commented on translations/pt-BR/README.md
> +<summary><b>Criar um Principal de Serviço do Azure</b></summary>
Criando um Azure Service Principal

2023-06-29 20:03 UTC, cyz commented on translations/pt-BR/README.md
> +A seguir, crie um Principal de Serviço do Azure, que é um tipo especial de conta que possui as permissões necessárias para autenticação do GitHub no Azure:
A seguir, crie um Azure Service Principal, que é um tipo especial de conta que possui as permissões necessárias para autenticação do GitHub no Azure:

2023-06-29 20:03 UTC, cyz commented on translations/pt-BR/README.md
> +2. Crie um Principal de Serviço com a função "contributor" que está autorizada a fazer alterações em todos os recursos dessa assinatura. Substitua $AZURE_SUBSCRIPTION_ID pelo ID encontrado no passo 1
Azure Service Principal

2023-06-29 20:04 UTC, cyz commented on translations/pt-BR/README.md
> +3. Copie a saída e adicione-a como um [segredo do repositório do GitHub](/../../settings/secrets/actions/new) com o nome `AZURE_CREDENTIALS`. (_Se esse link não funcionar, certifique-se de que você e
GitHub (com o H maiúsculo)

2023-06-29 20:07 UTC, cyz commented on translations/pt-BR/README.md
> +1. Você criou um Principal de Serviço do Azure e o salvou como um [segredo do repositório](/../../settings/secrets/) chamado `AZURE_CREDENTIALS`.
Azure Service Principal

2023-06-29 20:09 UTC, cyz commented on translations/pt-BR/README.md
> +1. Acesse [ações do repositório](/../../actions/workflows/web_app.yml). (_Se esse link não abrir o fluxo de trabalho "Build and deploy Python app", certifique-se de que você está lendo isso em sua pr
Acesse [Actions do repositório]

2023-06-29 20:10 UTC, cyz commented on translations/pt-BR/README.md
> +Ajude-nos a melhorar este repositório de modelo [nos informando e abrindo uma issue!](/../../issues/new).
link correto para abrir uma issue: https://github.com/education/codespaces-project-template-py/issues/new

2023-06-29 20:12 UTC, cyz commented
Olá @Corttezz, enviei alguns comentários para ajustes no arquivo.

2023-06-29 20:13 UTC, cyz requested changes
Olá @Corttezz, enviei alguns comentários para ajustes no arquivo. Por favor, avise se tiver dúvidas.

2023-07-02 16:57 UTC, Corttezz commented
@cyz Obrigado, consegue ver se está certinho agora?

2023-07-03 15:32 UTC, cyz approved these changes
Thank you @Corttezz, your PR is ready for approval!

Please @alfredodeza @WirelessLife or @saragibby can you accept?

2023-07-05 19:46 UTC, alfredodeza approved these changes

2023-07-05 20:12 UTC, merged